"""Markdown assembly and file output for the daily digest."""
from __future__ import annotations

from datetime import date
from pathlib import Path

from trendscope.digest.filters import FlaggedTicker
from trendscope.digest.news import Headline

DISCLAIMER = (
    "> Descriptive analytics only — not investment advice. Signal values are "
    "computed deterministically; the narrative section (when present) is "
    "LLM-generated from those values and may be imperfect."
)


def render_digest(
    as_of: date,
    breadth: dict[str, float] | None,
    flagged: list[FlaggedTicker],
    headlines: dict[str, list[Headline]],
    narrative: str | None,
) -> str:
    """Assemble the full digest markdown document."""
    parts: list[str] = [
        f"# TrendScope Daily Digest — {as_of.isoformat()}",
        "",
        DISCLAIMER,
        "",
        "## Market breadth",
        "",
    ]

    if breadth:
        parts += [
            f"- Tickers observed: {breadth.get('tickers_observed', 0):.0f}",
            f"- Above slow MA: {breadth.get('pct_above_slow_ma', 0):.0%}",
            f"- Positive 21d return: {breadth.get('pct_positive_21d', 0):.0%}",
            f"- Volume spikes: {breadth.get('pct_volume_spike', 0):.0%}",
        ]
    else:
        parts.append("_Breadth stats unavailable for this date._")

    parts += ["", "## Narrative", ""]
    parts.append(
        narrative
        if narrative
        else "_LLM narrative disabled (no ANTHROPIC_API_KEY configured or --no-llm)._"
    )

    parts += ["", f"## Flagged tickers ({len(flagged)})", ""]
    if not flagged:
        parts.append("_Nothing met the digest rules today._")

    for f in flagged:
        parts.append(f"### {f.ticker}")
        parts.extend(f"- {r}" for r in f.reasons)
        if f.metrics:
            metrics = ", ".join(f"{k}={v:.4f}" for k, v in sorted(f.metrics.items()))
            parts.append(f"- _metrics_: {metrics}")
        for h in headlines.get(f.ticker, []):
            publisher = f" — {h.publisher}" if h.publisher else ""
            parts.append(f"- 📰 {h.title}{publisher}")
        parts.append("")

    parts.append("---")
    parts.append("_Generated by trendscope._")
    return "\n".join(parts) + "\n"


def write_digest(text: str, digests_dir: Path, as_of: date) -> Path:
    """Write the digest to <digests_dir>/YYYY-MM-DD.md and return the path."""
    digests_dir.mkdir(parents=True, exist_ok=True)
    path = digests_dir / f"{as_of.isoformat()}.md"
    path.write_text(text)
    return path
